### ISSUE TITLE
הוספת הדיסקליימר לאתר

### ISSUE THREAD

**Issue by ekurer** [wiserdor/MilCalc#1]
למיטב הבנתי אלו תקציבים שלא אושרו בממשלה. כרגע כל מה שיש זו מצגת...
חבל להטעות אנשים, ממליץ להוסיף את הדיסקליימר הזה בבולד באתר ולא רק ברידמי

**Comment by wiserdor** [comment]
תודה על התגובה,
מסכים אנחנו נחשוב על ניסוח יותר טוב מביסוס המחשבון על קובץ הpdf וננסה להבהיר שיכול להיות שלא יאושר.
נעדכן בהקדם 💪

**Comment by wiserdor** [comment]
added at https://github.com/wiserdor/MilCalc/commit/34358dd98d8d79b451924a255b95305cb925c26d
