### ISSUE TITLE
Displaying grants for the wrong period

### ISSUE THREAD

**Issue by EladBox** [wiserdor/MilCalc#8]
Grants are shown for the year 2023 even though I did not select dates from the year 23
![image](https://github.com/wiserdor/MilCalc/assets/126517012/7b063f12-5dcc-4683-8760-57ede89d4013)

**Comment by wiserdor** [comment]
fixed thanks!
https://github.com/wiserdor/MilCalc/commit/96b0ba0ecd83b31e34d9aa0144e428812c6cf956
